package net.axollen.create_ice_creams.init;

import net.axollen.create_ice_creams.CreateIceCreamsMod;
import net.axollen.create_ice_creams.item.*;
import net.minecraft.core.Registry;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.Item;

public class CreateIceCreamsModItems {
   public static Item CONED_VANILLA_ICE_CREAM;
   public static Item VANILLA;
   public static Item CONE;
   public static Item CONED_VANILLA_SWEET_BERRIES_ICE_CREAM;
   public static Item CONED_VANILLA_CARROT_ICE_CREAM;
   public static Item CONED_VANILLA_GLOW_BERRIES_ICE_CREAM;
   public static Item CONED_VANILLA_CHORUS_FRUIT_ICE_CREAM;
   public static Item CONED_CHOCOLATE_ICE_CREAM;
   public static Item CHOCOLATE_CREAM;
   public static Item CONED_CHOCOLATE_SWEET_BERRIES_ICE_CREAM;
   public static Item CONED_CHOCOLATE_CARROT_ICE_CREAM;
   public static Item CONED_CHOCOLATE_GLOW_BERRIES_ICE_CREAM;
   public static Item CONED_CHOCOLATE_CHORUS_FRUIT_ICE_CREAM;
   public static Item TOFFEE_CREAM;
   public static Item CONED_TOFFEE_ICE_CREAM;
   public static Item CONED_TOFFEE_SWEET_BERRIES_ICE_CREAM;
   public static Item CONED_TOFFEE_CHORUS_FRUIT_ICE_CREAM;
   public static Item CONED_TOFFEE_CARROT_ICE_CREAM;
   public static Item CONED_TOFFEE_GLOW_BERRIES_ICE_CREAM;
   public static Item BUBBLEGUM_FLAVORED_CREAM;
   public static Item CONED_BUBBLEGUM_FLAVORED_ICE_CREAM;
   public static Item CONED_BUBBLEGUM_FLAVORED_SWEET_BERRIES_ICE_CREAM;
   public static Item CONED_BUBBLEGUM_FLAVORED_CARROT_ICE_CREAM;
   public static Item CONED_BUBBLEGUM_FLAVORED_GLOW_BERRIES_ICE_CREAM;
   public static Item CONED_BUBBLEGUM_FLAVORED_CHORUS_FRUIT_ICE_CREAM;
   public static Item MINT_CREAM;
   public static Item CONED_MINT_ICE_CREAM;
   public static Item CONED_MINT_SWEET_BERRIES_ICE_CREAM;
   public static Item CONED_MINT_CARROT_ICE_CREAM;
   public static Item CONED_MINT_GLOW_BERRIES_ICE_CREAM;
   public static Item CONED_MINT_CHORUS_FRUIT_ICE_CREAM;
   public static Item MYSTERY_CREAM;
   public static Item CONED_MYSTERY_ICE_CRAM;
   public static Item CONED_MYSTERY_ICE_CREM;
   public static Item CONED_MYSTERY_ICE_CRAEM;
   public static Item CONED_MYSTERY_ICE_CREAM;
   public static Item CONED_WATERMELON_ICE_CREAM;
   public static Item WATERMELON_CREAM;
   public static Item CONED_WATERMELON_SWEET_BERRIES_ICE_CREAM;
   public static Item CONED_WATERMELON_CARROT_ICE_CREAM;
   public static Item CONED_WATERMELON_GLOW_BERRIES_ICE_CREAM;
   public static Item CONED_WATERMELON_CHORUS_FRUIT_ICE_CREAM;
   public static Item CONED_VANILLA_FUSION_ICE_CREAM;
   public static Item CONED_CHOCOLATE_FUSION_ICE_CREAM;
   public static Item CONED_TOFFEE_FUSION_ICE_CREAM;
   public static Item CONED_BUBBLEGUM_FLAVORED_FUSION_ICE_CREAM;
   public static Item CONED_MINT_FUSION_ICE_CREAM;
   public static Item CONED_WATERMELON_FUSION_ICE_CREAM;
   public static Item HONEY_CREAM;
   public static Item CONED_HONEY_ICE_CREAM;
   public static Item CONED_HONEY_SWEET_BERRIES_ICE_CREAM;
   public static Item CONED_HONEY_CARROT_ICE_CREAM;
   public static Item CONED_HONEY_GLOW_BERRIES_ICE_CREAM;
   public static Item CONED_HONEY_CHORUS_FRUIT_ICE_CREAM;
   public static Item CONED_HONEY_FUSION_ICE_CREAM;
   public static Item APPLE_CREAM;
   public static Item CONED_APPLE_ICE_CREAM;
   public static Item CONED_APPLE_SWEET_BERRIES_ICE_CREAM;
   public static Item CONED_APPLE_CARROT_ICE_CREAM;
   public static Item CONED_APPLE_GLOW_BERRIES_ICE_CREAM;
   public static Item CONED_APPLE_CHORUS_FRUIT_ICE_CREAM;
   public static Item CONED_APPLE_FUSION_ICE_CREAM;
   public static Item COOKIE_CREAM;
   public static Item CONED_COOKIE_ICE_CREAM;
   public static Item CONED_COOKIE_SWEET_BERRIES_ICE_CREAM;
   public static Item CONED_COOKIE_CARROT_ICE_CREAM;
   public static Item CONED_COOKIE_GLOW_BERRIES_ICE_CREAM;
   public static Item CONED_COOKIE_CHORUS_FRUIT_ICE_CREAM;
   public static Item CONED_COOKIE_FUSION_ICE_CREAM;
   public static Item CACTUS_CREAM;
   public static Item CONED_CACTUS_ICE_CREAM;
   public static Item CONED_CACTUS_SWEET_BERRIES_ICE_CREAM;
   public static Item CONED_CACTUS_CARROT_ICE_CREAM;
   public static Item CONED_CACTUS_GLOW_BERRIES_ICE_CREAM;
   public static Item CONED_CACTUS_CHORUS_FRUIT_ICE_CREAM;
   public static Item CONED_CACTUS_FUSION_ICE_CREAM;
   public static Item BEETROOT_CREAM;
   public static Item CONED_BEETROOT_ICE_CREAM;
   public static Item CONED_BEETROOT_SWEET_BERRIES_ICE_CREAM;
   public static Item CONED_BEETROOT_CARROT_ICE_CREAM;
   public static Item CONED_BEETROOT_GLOW_BERRIES_ICE_CREAM;
   public static Item CONED_BEETROOT_CHORUS_FRUIT_ICE_CREAM;
   public static Item CONED_BEETROOT_FUSION_ICE_CREAM;
   public static Item POTATO_CREAM;
   public static Item CONED_POTATO_ICE_CREAM;
   public static Item CONED_POTATO_SWEET_BERRIES_ICE_CREAM;
   public static Item CONED_POTATO_CARROT_ICE_CREAM;
   public static Item CONED_POTATO_GLOW_BERRIES_ICE_CREAM;
   public static Item CONED_POTATO_CHORUS_FRUIT_ICE_CREAM;
   public static Item CONED_POTATO_FUSION_ICE_CREAM;

   public static void register() {
      CONED_VANILLA_ICE_CREAM = reg("coned_vanilla_ice_cream", new ConedVanillaIceCreamItem());
      VANILLA = reg("vanilla", new VanillaItem());
      CONE = reg("cone", new ConeItem());
      CONED_VANILLA_SWEET_BERRIES_ICE_CREAM = reg("coned_vanilla_sweet_berries_ice_cream", new ConedVanillaSweetBerriesIceCreamItem());
      CONED_VANILLA_CARROT_ICE_CREAM = reg("coned_vanilla_carrot_ice_cream", new ConedVanillaCarrotIceCreamItem());
      CONED_VANILLA_GLOW_BERRIES_ICE_CREAM = reg("coned_vanilla_glow_berries_ice_cream", new ConedVanillaGlowBerriesIceCreamItem());
      CONED_VANILLA_CHORUS_FRUIT_ICE_CREAM = reg("coned_vanilla_chorus_fruit_ice_cream", new ConedVanillaChorusFruitIceCreamItem());
      CONED_CHOCOLATE_ICE_CREAM = reg("coned_chocolate_ice_cream", new ChocolateIceCreamItem());
      CHOCOLATE_CREAM = reg("chocolate_cream", new ChocolateCreamItem());
      CONED_CHOCOLATE_SWEET_BERRIES_ICE_CREAM = reg("coned_chocolate_sweet_berries_ice_cream", new ConedChocolateSweetBerriesIceCreamItem());
      CONED_CHOCOLATE_CARROT_ICE_CREAM = reg("coned_chocolate_carrot_ice_cream", new ConedChocolateCarrotIceCreamItem());
      CONED_CHOCOLATE_GLOW_BERRIES_ICE_CREAM = reg("coned_chocolate_glow_berries_ice_cream", new ConedChocolateGlowBerriesIceCreamItem());
      CONED_CHOCOLATE_CHORUS_FRUIT_ICE_CREAM = reg("coned_chocolate_chorus_fruit_ice_cream", new ConedChocolateChorusFruitIceCreamItem());
      TOFFEE_CREAM = reg("toffee_cream", new ToffeeCreamItem());
      CONED_TOFFEE_ICE_CREAM = reg("coned_toffee_ice_cream", new ConedToffeeIceCreamItem());
      CONED_TOFFEE_SWEET_BERRIES_ICE_CREAM = reg("coned_toffee_sweet_berries_ice_cream", new ConedToffeeSweetBerriesIceCreamItem());
      CONED_TOFFEE_CHORUS_FRUIT_ICE_CREAM = reg("coned_toffee_chorus_fruit_ice_cream", new ConedToffeeChorusFruitIceCreamItem());
      CONED_TOFFEE_CARROT_ICE_CREAM = reg("coned_toffee_carrot_ice_cream", new ConedToffeCarrotIceCreamItem());
      CONED_TOFFEE_GLOW_BERRIES_ICE_CREAM = reg("coned_toffee_glow_berries_ice_cream", new ConedToffeeGlowBerriesIceCreamItem());
      BUBBLEGUM_FLAVORED_CREAM = reg("bubblegum_flavored_cream", new BubblegumFlavoredCreamItem());
      CONED_BUBBLEGUM_FLAVORED_ICE_CREAM = reg("coned_bubblegum_flavored_ice_cream", new ConedBubblegumFlavoredIceCreamItem());
      CONED_BUBBLEGUM_FLAVORED_SWEET_BERRIES_ICE_CREAM = reg("coned_bubblegum_flavored_sweet_berries_ice_cream", new ConedBubblegumFlavoredSweetBerriesIceCreamItem());
      CONED_BUBBLEGUM_FLAVORED_CARROT_ICE_CREAM = reg("coned_bubblegum_flavored_carrot_ice_cream", new ConedBubblegumFlavoredCarrotIceCreamItem());
      CONED_BUBBLEGUM_FLAVORED_GLOW_BERRIES_ICE_CREAM = reg("coned_bubblegum_flavored_glow_berries_ice_cream", new ConedBubblegumFlavoredGlowBerriesIceCreamItem());
      CONED_BUBBLEGUM_FLAVORED_CHORUS_FRUIT_ICE_CREAM = reg("coned_bubblegum_flavored_chorus_fruit_ice_cream", new ConedBubblegumFlavoredChorusFruitIceCreamItem());
      MINT_CREAM = reg("mint_cream", new MintCreamItem());
      CONED_MINT_ICE_CREAM = reg("coned_mint_ice_cream", new ConedMintIceCreamItem());
      CONED_MINT_SWEET_BERRIES_ICE_CREAM = reg("coned_mint_sweet_berries_ice_cream", new ConedMintSweetBerriesIceCreamItem());
      CONED_MINT_CARROT_ICE_CREAM = reg("coned_mint_carrot_ice_cream", new ConedMintCarrotIceCreamItem());
      CONED_MINT_GLOW_BERRIES_ICE_CREAM = reg("coned_mint_glow_berries_ice_cream", new ConedMintGlowBerriesIceCreamItem());
      CONED_MINT_CHORUS_FRUIT_ICE_CREAM = reg("coned_mint_chorus_fruit_ice_cream", new ConedMintChorusFruitIceCreamItem());
      MYSTERY_CREAM = reg("mystery_cream", new MysteryCreamItem());
      CONED_MYSTERY_ICE_CRAM = reg("coned_mystery_ice_cram", new ConedMysteryIceCramItem());
      CONED_MYSTERY_ICE_CREM = reg("coned_mystery_ice_crem", new ConedMysteryIceCremItem());
      CONED_MYSTERY_ICE_CRAEM = reg("coned_mystery_ice_craem", new ConedMysteryIceCraemItem());
      CONED_MYSTERY_ICE_CREAM = reg("coned_mystery_ice_cream", new ConedMysteryIceCreamItem());
      CONED_WATERMELON_ICE_CREAM = reg("coned_watermelon_ice_cream", new ConedWatermelonIceCreamItem());
      WATERMELON_CREAM = reg("watermelon_cream", new WatermelonCreamItem());
      CONED_WATERMELON_SWEET_BERRIES_ICE_CREAM = reg("coned_watermelon_sweet_berries_ice_cream", new ConedWatermelonSweetBerriesIceCreamItem());
      CONED_WATERMELON_CARROT_ICE_CREAM = reg("coned_watermelon_carrot_ice_cream", new ConedWatermelonCarrotIceCreamItem());
      CONED_WATERMELON_GLOW_BERRIES_ICE_CREAM = reg("coned_watermelon_glow_berries_ice_cream", new ConedWatermelonGlowBerriesIceCreamItem());
      CONED_WATERMELON_CHORUS_FRUIT_ICE_CREAM = reg("coned_watermelon_chorus_fruit_ice_cream", new ConedWatermelonChorusFruitIceCreamItem());
      CONED_VANILLA_FUSION_ICE_CREAM = reg("coned_vanilla_fusion_ice_cream", new ConedVanillaFusionIceCreamItem());
      CONED_CHOCOLATE_FUSION_ICE_CREAM = reg("coned_chocolate_fusion_ice_cream", new ConedChocolateFusionIceCreamItem());
      CONED_TOFFEE_FUSION_ICE_CREAM = reg("coned_toffee_fusion_ice_cream", new ConedToffeeFusionIceCreamItem());
      CONED_BUBBLEGUM_FLAVORED_FUSION_ICE_CREAM = reg("coned_bubblegum_flavored_fusion_ice_cream", new ConedBubblegumFlavoredFusionIceCreamItem());
      CONED_MINT_FUSION_ICE_CREAM = reg("coned_mint_fusion_ice_cream", new ConedMintFusionIceCreamItem());
      CONED_WATERMELON_FUSION_ICE_CREAM = reg("coned_watermelon_fusion_ice_cream", new ConedWatermelonFusionIceCreamItem());
      HONEY_CREAM = reg("honey_cream", new HoneyCreamItem());
      CONED_HONEY_ICE_CREAM = reg("coned_honey_ice_cream", new ConedHoneyIceCreamItem());
      CONED_HONEY_SWEET_BERRIES_ICE_CREAM = reg("coned_honey_sweet_berries_ice_cream", new ConedHoneySweetBerriesIceCreamItem());
      CONED_HONEY_CARROT_ICE_CREAM = reg("coned_honey_carrot_ice_cream", new ConedHoneyCarrotIceCreamItem());
      CONED_HONEY_GLOW_BERRIES_ICE_CREAM = reg("coned_honey_glow_berries_ice_cream", new ConedHoneyGlowBerriesIceCreamItem());
      CONED_HONEY_CHORUS_FRUIT_ICE_CREAM = reg("coned_honey_chorus_fruit_ice_cream", new ConedHoneyChorusFruitIceCreamItem());
      CONED_HONEY_FUSION_ICE_CREAM = reg("coned_honey_fusion_ice_cream", new ConedHoneyFusionIceCreamItem());
      APPLE_CREAM = reg("apple_cream", new AppleCreamItem());
      CONED_APPLE_ICE_CREAM = reg("coned_apple_ice_cream", new ConedAppleIceCreamItem());
      CONED_APPLE_SWEET_BERRIES_ICE_CREAM = reg("coned_apple_sweet_berries_ice_cream", new ConedAppleSweetBerriesIceCreamItem());
      CONED_APPLE_CARROT_ICE_CREAM = reg("coned_apple_carrot_ice_cream", new ConedAppleCarrotIceCreamItem());
      CONED_APPLE_GLOW_BERRIES_ICE_CREAM = reg("coned_apple_glow_berries_ice_cream", new ConedAppleGlowBerriesIceCreamItem());
      CONED_APPLE_CHORUS_FRUIT_ICE_CREAM = reg("coned_apple_chorus_fruit_ice_cream", new ConedAppleChorusFruitIceCreamItem());
      CONED_APPLE_FUSION_ICE_CREAM = reg("coned_apple_fusion_ice_cream", new ConedAppleFusionIceCreamItem());
      COOKIE_CREAM = reg("cookie_cream", new CookieCreamItem());
      CONED_COOKIE_ICE_CREAM = reg("coned_cookie_ice_cream", new ConedCookieIceCreamItem());
      CONED_COOKIE_SWEET_BERRIES_ICE_CREAM = reg("coned_cookie_sweet_berries_ice_cream", new ConedCookieSweetBerriesIceCreamItem());
      CONED_COOKIE_CARROT_ICE_CREAM = reg("coned_cookie_carrot_ice_cream", new ConedCookieCarrotIceCreamItem());
      CONED_COOKIE_GLOW_BERRIES_ICE_CREAM = reg("coned_cookie_glow_berries_ice_cream", new ConedCookieGlowBerriesIceCreamItem());
      CONED_COOKIE_CHORUS_FRUIT_ICE_CREAM = reg("coned_cookie_chorus_fruit_ice_cream", new ConedCookieChorusFruitIceCreamItem());
      CONED_COOKIE_FUSION_ICE_CREAM = reg("coned_cookie_fusion_ice_cream", new ConedCookieFusionIceCreamItem());
      CACTUS_CREAM = reg("cactus_cream", new CactusCreamItem());
      CONED_CACTUS_ICE_CREAM = reg("coned_cactus_ice_cream", new ConedCactusIceCreamItem());
      CONED_CACTUS_SWEET_BERRIES_ICE_CREAM = reg("coned_cactus_sweet_berries_ice_cream", new ConedCactusSweetBerriesIceCreamItem());
      CONED_CACTUS_CARROT_ICE_CREAM = reg("coned_cactus_carrot_ice_cream", new ConedCactusCarrotIceCreamItem());
      CONED_CACTUS_GLOW_BERRIES_ICE_CREAM = reg("coned_cactus_glow_berries_ice_cream", new ConedCactusGlowBerriesIceCreamItem());
      CONED_CACTUS_CHORUS_FRUIT_ICE_CREAM = reg("coned_cactus_chorus_fruit_ice_cream", new ConedCactusChorusFruitIceCreamItem());
      CONED_CACTUS_FUSION_ICE_CREAM = reg("coned_cactus_fusion_ice_cream", new ConedCactusFusionIceCreamItem());
      BEETROOT_CREAM = reg("beetroot_cream", new BeetrootCreamItem());
      CONED_BEETROOT_ICE_CREAM = reg("coned_beetroot_ice_cream", new ConedBeetrootIceCreamItem());
      CONED_BEETROOT_SWEET_BERRIES_ICE_CREAM = reg("coned_beetroot_sweet_berries_ice_cream", new ConedBeetrootSweetBerriesIceCreamItem());
      CONED_BEETROOT_CARROT_ICE_CREAM = reg("coned_beetroot_carrot_ice_cream", new ConedBeetrootCarrotIceCreamItem());
      CONED_BEETROOT_GLOW_BERRIES_ICE_CREAM = reg("coned_beetroot_glow_berries_ice_cream", new ConedBeetrootGlowBerriesIceCreamItem());
      CONED_BEETROOT_CHORUS_FRUIT_ICE_CREAM = reg("coned_beetroot_chorus_fruit_ice_cream", new ConedBeetrootChorusFruitIceCreamItem());
      CONED_BEETROOT_FUSION_ICE_CREAM = reg("coned_beetroot_fusion_ice_cream", new ConedBeetrootFusionIceCreamItem());
      POTATO_CREAM = reg("potato_cream", new PotatoCreamItem());
      CONED_POTATO_ICE_CREAM = reg("coned_potato_ice_cream", new ConedPotatoIceCreamItem());
      CONED_POTATO_SWEET_BERRIES_ICE_CREAM = reg("coned_potato_sweet_berries_ice_cream", new ConedPotatoSweetBerriesIceCreamItem());
      CONED_POTATO_CARROT_ICE_CREAM = reg("coned_potato_carrot_ice_cream", new ConedPotatoCarrotIceCreamItem());
      CONED_POTATO_GLOW_BERRIES_ICE_CREAM = reg("coned_potato_glow_berries_ice_cream", new ConedPotatoGlowBerriesIceCreamItem());
      CONED_POTATO_CHORUS_FRUIT_ICE_CREAM = reg("coned_potato_chorus_fruit_ice_cream", new ConedPotatoChorusFruitIceCreamItem());
      CONED_POTATO_FUSION_ICE_CREAM = reg("coned_potato_fusion_ice_cream", new ConedPotatoFusionIceCreamItem());
   }

   private static Item reg(String name, Item item) {
      return Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(CreateIceCreamsMod.MODID, name), item);
   }
}
